name: Build and Deploy

on:
  pull_request:
    branches:
      - dev

jobs:

  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build with Gradle
        run: bash gradlew checkstyleMain

  lint-css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Stylelint
        run: npm install -g stylelint stylelint-config-standard

      - name: Lint CSS with Stylelint
        run: stylelint '**/style.css'

  lint-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Lint HTML with HTMLHint
        run: htmlhint 'src/main/**/*.html'

  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install ESLint
        run: npm install eslint --save-dev

      - name: Lint JS with ESLint
        run: eslint 'src/main/resources/static/javascript/webapp-js/*.js'
