name: Build and Deploy

on:
  push:
    branches:
      - dev

jobs:
    checkstyle:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: 17
            distribution: 'adopt'

        - name: Build with Gradle
          run: bash gradlew checkstyleMain